server:
  log_level: info
  http_listen_port: 3101

clients:    
  - url: http://loki:3100/loki/api/v1/push

positions:
  filename: /tmp/position/positions.yaml

scrape_configs:
#  - job_name: syslog
#    syslog:
#      listen_address: 0.0.0.0:1514
#      idle_timeout: 60s
#      label_structured_data: yes
#      labels:
#        job: "syslog"
#        hospital: ${HOSPCODE}
#        zone: ${ZONE}
#        province: ${PROVINCE}
#        group: ${GROUP}
#    relabel_configs:
#      - source_labels: ['__syslog_message_hostname']
#        target_label: 'host'

  - job_name: system
    pipeline_stages:
    static_configs:
    - targets:
      - localhost
      labels:
        job: varlogs
        __path__: /host/var/log/*

  - job_name: containers
    static_configs:
    - targets:
      - localhost
      labels:
        job: containerlogs
        __path__: /var/lib/docker/containers/*/*log

    pipeline_stages:
    - json:
        expressions:
          output: log
          stream: stream
          attrs:
    - json:
        expressions:
          tag:
        source: attrs
    - regex:
        expression: (?P<image_name>(?:[^|]*[^|])).(?P<container_name>(?:[^|]*[^|])).(?P<image_id>(?:[^|]*[^|])).(?P<container_id>(?:[^|]*[^|]))
        source: tag
    - timestamp:
        format: RFC3339Nano
        source: time
    - labels:
        tag:
        stream:
        image_name:
        container_name:
        image_id:
        container_id:
    - output:
        source: output